### ISSUE TITLE
Expanding requirements file

### ISSUE THREAD

**Issue by kornicameister** [zsimic/setupmeta#29]
Hi @zsimic 

Very useful library and indeed it helps a lot with avoiding the repeated boilerplate.
Wonder if you considered following use case. I have a requirements file, correctly test requirements that I decided to split up into categories thus having something like below:

```
tox==3.13.2
-r requirements/yapf.txt
-r requirements/mypy.txt
-r requirements/flake8.txt
-r requirements/tests.txt
```

`setupmeta` does not currently traverse the linked files although that it obviously a correct form that if fed to `pip` results in traversing those files.

What do you think about baking that into the `setupmeta`?

**Comment by kornicameister** [comment]
That's actually really akward, because I ran the code like so `parse_requirements('./test-requirements.txt', session=PipSession())`, which is basically what you use in `setupmeta` and it expanded the requirements as I would expect it to do.

**Comment by zsimic** [comment]
Sorry about late reply, was away on vacation.

I just tried this, and it does seem to work (I didn't know it did :) not that people did this).
Do you have a link you can share to your case that doesn't seem to work?

**Comment by kornicameister** [comment]
No problem, I came back from my holiday season as well. About the case, you can check [this](https://github.com/kornicameister/asyncpg-migrate/blob/master/setup.py) out. If you clone that, install all requirements (if you want to), running `python setup.py explain` ought to reveal to you sth like:

```
tests_require: (test-requirements.txt        ) ["tox==3.13.2", "setupmeta==2.6.3", "-r requirements/yapf.txt", "-r requirements/mypy.txt", "-r requirements/flake8.txt", "-r requirements/tests.txt"]
```

along `tests_require`.

**Comment by zsimic** [comment]
Found the issue: it's due to the approach I took... I do a "pre-parsing" of the reqs file (in order to implement [this](https://github.com/zsimic/setupmeta/blob/master/docs/requirements.rst)), and then if any of the lines are "complex" (ie: not a simple dep declaration, like a `-r`), then indeed `parse_requirements()` is called, but in a temp folder...

In your case, `-r requirements/yapf.txt` etc then doesn't point to an existing file anymore (due to temp folder).

I'd have to rethink this, and call `parse_requirements()` first (get rid of the "pre-parsing"), but that is going to be tricky because I pre-parse in order to take into account comments such as `# pineed` etc

The real long-term solution to this would be a proper dependency system in python :) `requirements.txt` is a pain, and the hacks/conventions often don't cut it, can't replace a proper dependency system :)

**Comment by zsimic** [comment]
This should fix this: https://github.com/zsimic/setupmeta/issues/29 but only for test requirements (as that one is not "abstracted" anyway by setupmeta).

Will need to re-think this for regular requirements.txt file, and see what can be done there, in order to both keep the abstractions, and let pip parse the full file properly

**Comment by kornicameister** [comment]
About proper dependency files, you might want to check pipenv and consider supporting that. There are so called Pipfile and Pipfile.lock which should sound fairly familiar.

**Comment by blueyed** [comment]
(FWIW, I cannot recommend using pipenv - will not elaborate, but there are blog posts about this (IIRC).)

**Comment by kornicameister** [comment]
Oh my lord...it seems my initial enthusiasm was...ehhh...thx for pointing me to that

**Comment by kornicameister** [comment]
@zsimic I feel like my issue has been solved, so feel free to close it.
@blueyed thx once again for dropping me a line about `pipenv` disadvantages. I already pushed [removing](https://github.com/kornicameister/dotfiles/pull/272) that from my environment.

**Comment by zsimic** [comment]
I try pipenv every now and then, but yeah turns out it's not that great IMHO.
I reported a few bugs, and give it a go every now and then to see if it improved.

I tried supporting pipfile, but there's no standard lib to parse toml, and they do a weird copy-paste approach to take toml parsing in (they call it "vendoring"... but it's just copy-pasting a lib in one's own code, like this: https://github.com/pypa/pipenv/tree/master/pipenv/vendor).

Couldn't write a reasonable toml parser, and kept running into weirdnesses, so I gave up.

**Comment by zsimic** [comment]
setupmeta 2.6.4 has a fix for this (but only for test requirements, not the "main" requirements file)

**Comment by Kilo59** [comment]
> Couldn't write a reasonable toml parser, and kept running into weirdnesses, so I gave up.

IMO the better way to do this is by parsing the lock file as it is JSON. This is what do for several of my projects. Its fairly simple. 
I'll try to post a PR that... 
1. checks for the Pipfile.lock if there's no requirements file. 
2. Parses the non-dev dependencies
3. Should I include the marker info with the package name? (this breaks the pip install with very old versions of pip)

**Comment by zsimic** [comment]
setupmeta is trying to be convenient, and reduce boilerplate by applying most common good practice.
If `Pipfile` is a very common good practice, then it makes sense to try and reduce the boilerplate (in `setup.py`) associated to that common good practice yes.

I am not super familiar with pipenv anymore (gave it a good try, submitted a few issues etc), but IIUC, the `install_requires` section of `setup.py` should be auto-filled from `Pipfile`, NOT`Pipfile.lock`.

Taking from the main example on pypa/pipfile github page, we have for example:
```
[packages]
requests = { extras = ['socks'] }
records = '>0.5.0'
```

Which translates to `Pipfile.json`:
```
"records": {"version": "==0.5.2"},
"requests": {"version": "==2.18.4"},
```

The above shows that we definitely can't use the `.json` file, as all it does is "snapshotted pins" of whatever versions complied to the `Pipfile` when the build was ran.

I think here `install_requires` should clearly correspond to the `Pipfile` itself, ie: it should look like:
```
install_requires=["requests", "records>0.5.0", ...],
```
+ even more stuff in `extras_require`

So: I think we can't take the shortcut and use `Pipfile.json`, that wouldn't correspond to the intent of the project (which is conveyed by `Pipfile` itself)

**Comment by Kilo59** [comment]
> The above shows that we definitely can't use the .lock file, as all it does is "snapshotted pins" of whatever versions were resolved from the Pipfile when the last venv build was ran.

I use `Pipenv` extensively.
The way that I've typically seen projects using the Pipfile.lock isn't to pin specific dependencies, just like most `install_requires` lists don't actually specify versions.

If users need an exact match of the locked dependencies they would do a `pipenv sync` not a pip/setup install.

So in your example a lock file of `"records": {"version": "==0.5.2"}, "requests": {"version": "==2.18.4"}` would endup with `install_requires=["requests","records"]`

There are sure to be lots of use-cases where this doesn't fit but IMO it's probably a good approximation what most Pipenv users want their setup.py to look like.

BTW I totally understand if you still don't want to support this 😄.

**Comment by zsimic** [comment]
If I understand correctly, if you specify this in your `Pipfile`:
```
[packages]
records = '>0.5.0'
```

That means that you want to advertise `install_requires=["records>0.5.0"]` for your library no?

It would be easier to just read the json file and ignore version constraints from `Pipfile` yes, but I'm thinking that's not what the author of the `Pipfile` tried to specify... so it would be not really correct.

**Comment by zsimic** [comment]
With a recent change to `pip._internal` (see issue #49), I decided to stop using `pip._internal` and refactor/review the code so that it doesn't need it.

This in turn made it possible to support this nested `--requirements` suggestion.

Happy to let you know that setupmeta 2.7.3 supports this now! I added tests to exercise it etc, it should properly auto-fill `install_requires` (and/or `tests_require`) with files such as you are using here.

**Comment by kornicameister** [comment]
@zsimic you are the boss!

**Comment by kornicameister** [comment]
![image](https://user-images.githubusercontent.com/1029674/80997688-facd5300-8e41-11ea-9a06-32f723d0899d.png)

top left => `2.7.2`
right side => `2.7.3`
bottom left => current requirements.

for me it works. I think that upgrading `pip` was not really necessary although you mentioned newer version, so I just picked it up as well.

feel free to close it down, it works flawlessly :)

**Comment by zsimic** [comment]
Awesome :) You don't need latest pip for this (grabbing it is fine, but unrelated to setupmeta).

I was just saying latest pip 20.1 broke setupmeta, which was the motivation to stop using `pip._internal` from now on :) (not the 1st time it happens)
Using a `._internal` sounds like begging for trouble anyway... unfortunately `pip` team refuses to commit to an API, so they did the `._internal` choice, warning people not to use it, but since there's no alternative many users do...)

Noting from your screenshot: you don't need to mention setupmeta anywhere other than `setup_requires`. It won't hurt doing so, but it does nothing really (unless you for some reason `import setupmeta` in your tests...)

Most vanilla usage of setupmeta is:
- have `setup_requires=["setupmeta"]` in your setup.py
  - optionally, you can pin to a specific version, like: `setup_requires=["setupmeta==2.7.3"]`
- `rm -rf .eggs` when you want setuptools to upgrade to latest version (unfortunately, setuptools doesn't do auto-upgrade)

**Comment by zsimic** [comment]
Oh, BTW try: `python setup.py explain -d` -> that will show you which auto-filled req comes from which file (with line number)

The general `setup.py explain` just mentions which file the requirement came from overall (not going into details as to which included file specifically each bit came from)

`setup.py explain -d` (or `--dependencies` for long) shows that detail, and shows the auto-filled requirements only.

**Comment by kornicameister** [comment]
I have `setupmeta` in `setup_requires` as visible [here](https://github.com/kornicameister/axion/blob/master/setup.py#L16). Reason for having it in `test-requirements` was having dependabot to bump it. I was not aware that you can pit a version in `setup_requires` although if you can do that in `install_requires` why not in `setup_requires`. 

My only concern is just having dependabot to notify me that you've released another version.

**Comment by kornicameister** [comment]
> Oh, BTW try: `python setup.py explain -d` -> that will show you which auto-filled req comes from which file (with line number)
> 
> The general `setup.py explain` just mentions which file the requirement came from overall (not going into details as to which included file specifically each bit came from)
> 
> `setup.py explain -d` (or `--dependencies` for long) shows that detail, and shows the auto-filled requirements only.

this one rocks!

**Comment by zsimic** [comment]
I'll check dependabot, not familiar with it :)

Maybe dependabot could also look at `setup_requires` for convenience, since things like setupmeta (or setuptools_scm etc) have to use it :)

`pip install setupmeta` or having it in `tests_require` etc is fine to do, it's just a no-op :)
