### ISSUE TITLE
auto versioning from tag

### ISSUE THREAD

**Issue by Poil** [zsimic/setupmeta#32]
Hey,

I'm looking your module that seems great, but why you choose the tag format vX.X.X and not only X.X.X ?

Best regards

**Comment by zsimic** [comment]
Because that's how github does it by default, and several things IIUC consider that the norm

setupmeta will however internally consider `1.0.0` to be also a version tag (as well as `v1.0.0`).

It will prefix with `v` when bumping itself, but if you manually assign a tag `X.X.X`, it will use it

**Comment by zsimic** [comment]
Do you know if there's any form preferred other another?
I'd love to be as vanilla as possible in setupmeta, embracing the most common conventions

I looked around again, and I see that there are examples of both forms, like:

- using `v`:
https://github.com/psf/requests
https://github.com/pypa/pipenv
https://github.com/pypa/setuptools

- NOT using `v`:
https://github.com/pypa/pip
https://github.com/pypa/twine
https://github.com/pallets/click
https://github.com/django/django

**Comment by Poil** [comment]
Thanks, very interesting, it's look like the "v" comes from a recommendation of github for tagging.
I don't know if there is a preferred form, I was just curious, personally I don't like suffixing something that are already typed.
Had you tried PBR package (https://docs.openstack.org/pbr/latest/) before writing setupmeta ?

**Comment by zsimic** [comment]
I tried `pbr`, but it doesn't really try and reduce copy-paste boilerplate, it just moves it to `setup.cfg` (an extra file you now *have* to have)

It's also quite opinionated, for example, you can't define `name="myproject"` in `setup.py`, now you have to state it in `setup.cfg`... 
If you do state `version="1.0"` in your `setup.py`, it gets completely ignored with pbr etc.

Also, it has no introspection (like `setup.py explain` from setupmeta).

setupmeta tries to be as unobtrusive as possible, nothing's really required, you don't have to have git tags (a hardcoded version is taken into account, and even bumped properly), any key/value you explicitly set in `setup.py -> setup()` is always taken as-is, etc.

**Comment by zsimic** [comment]
Regarding tags, they're not "typed" unfortunately, they're just strings.

In my experience, I noticed that prefixing with `v`, like `vX.X.X` is probably a bit safer.
When looking for last version tag, one can do:
- `git describe --match '*.*'` -> this matches any tag with a `.` in it, hoping that tags with dots are indeed version tags, that no one added a tag `foo.bar` for example (this is the filter setupmeta currently uses internally, in order to support tags without a leading `v` as well)
- or `git describe --match 'v*.*'` -> this would match tags starting with `v` and having a dot, this would actually be safer (would ignore tags like `foo.bar`, but would still be fooled by say `voo.bar`)

`--match` is unfortunately a glob (not a regex) in git, not sure if there's a way do express "look for number(s) dot number(s)...
