### ISSUE TITLE
Fetch remote before version tagging

### ISSUE THREAD

**Issue by patricksanders** [zsimic/setupmeta#57]
When running a command such as `python setup.py version --bump patch --commit --push` to push a version tag, the tag may be created on an outdated commit if the user (me) forgets to pull the most recent changes for the branch (which I did). It would be nice to have an option to either:
- pull from the remote tracking branch and then apply the tag (maybe `python setup.py version --sync-branch --bump patch --commit --push`)
- fetch the remote tracking branch and fail the command if HEAD is out of date (maybe `python setup.py version --fetch --bump patch --commit --push`)

**Comment by zsimic** [comment]
That's an excellent point, I think running `git --fetch` systematically (no flag needed) and then double-checking that `HEAD` is still up-to-date is the right thing to do.

It's hard to anticipate otherwise if user wants pull or rebase etc, but it makes sense that intent when bumping is that it is done on `HEAD` on configured branch indeed!

**Comment by zsimic** [comment]
Will release tomorrow: https://github.com/zsimic/setupmeta/pull/58

**Comment by patricksanders** [comment]
Excellent, thank you!
