### ISSUE TITLE
Add tests to PyPI sdist

### ISSUE THREAD

**Issue by jayvdb** [zsimic/setupmeta#60]
Distros need to run tests before promoting packages, and this is especially important here as setuptools is regularly changing in quite fundamental ways that can break tools trying to play nicely with it.

**Comment by zsimic** [comment]
Are you suggesting to bundle setupmeta's `tests/` folder in the published sdist?

Do you mean to run setupmeta's tests from your own or?

**Comment by jayvdb** [comment]
Yes please.

To run the tests inside a isolated VM used to build an RPM for openSUSE.
https://build.opensuse.org/package/show/home:jayvdb:py-new/python-setupmeta

**Comment by zsimic** [comment]
I've adapted `test_check_dependencies` so that it exercises `check --deptree` command only when invoked from a venv.

`check --deptree` is a convenience thing, that just saves you the trouble of running `pip install pipdeptree` (or some similar tool).

You should be able now to run just `pytest` (without excluding anything), and it should work fine.

Let's see if that solves the issue for you. I looked into bundling the tests, but they would triple the size of the shipped egg/wheel... 
The size isn't necessarily an issue, but wondering if this will solve the issue for you.

Even if I bundle the tests with sdist, I will have to fine-tune a few things I think because the tests do assume they are ran from a venv created by tox right now.

Another alternative you have is to use tox (if that's possible), I am guessing it would be something like this in the `.spec`:
```
BuildRequires:  %{python_module tox}
...
%check
git config ..
...
tox -e py
```

(running just `tox` would exercise all python versions, `tox -e py` is a simple way to run with just "current python", like for example in setupmeta's own github action: https://github.com/zsimic/setupmeta/blob/master/.github/workflows/tests.yml#L28 )

**Comment by zsimic** [comment]
Merged https://github.com/zsimic/setupmeta/pull/62 it should solve both issues:
- `test_check_dependencies` should now work with or without a venv
- `test_wheel` removed, unused code (the commands it was for retired)

Changes are on master branch currently, I will release setupmeta 2.0.8 with it tomorrow morning.

**Comment by jayvdb** [comment]
Nice.

If you also publish a wheel, the increased size of the sdist shouldnt effect too many users.

**Comment by zsimic** [comment]
Yes, I publish an egg for each supported version + a universal wheel + sdist: https://pypi.org/project/setupmeta/#files

OK, let's see if this helps you with the testing as-is now.
If you'd still prefer to have the tests bundled in the sdist, let me know (I'll need to figure out how to bundle it with the sdist, but not the wheel or eggs :) )

**Comment by jayvdb** [comment]
There is nothing I can do until there is a new version number on PyPI , and the sdists has tests.  Until then I just sit tight, unless there is dev work that I can do to help, or testing needed before a release, etc.

Normally tests just need to be mentioned in `MANIFEST.in`, but I havent used eggs for a decade so I have no idea how that works with modern setuptools.  It used to be that eggs were roughly the same as wheels. Oh how times have changed.

**Comment by zsimic** [comment]
2.8.0 released now (sorry, got around to it later than I wanted)

Let's see if this 2.8.0 version, makes your life simpler enough.
If it doesn't, please let me know and I will explore bundling those tests.

Bundling data in packages is unfortunately not trivial (last time I looked), it's often not as simple as it looks at first :) I did find so far that a `graft` is what works best most of the time...

**Comment by jayvdb** [comment]
Creating releases without adding tests to PyPI creates more work for me ;-)  Once the tests are in PyPI sdists, we have tools that allow upgrading to occur on autopilot.

`graft` is simpler, but it will include dirty files generated during test runs, such as .pyc files, and anything else.

`recursive-include tests *.py *.txt ...` is safer, but lots longer.

https://pypi.org/project/check-manifest/ can be helpful.

**Comment by zsimic** [comment]
I've prepared a PR here to release tomorrow: https://github.com/zsimic/setupmeta/pull/63

I've checked that the tests (and test samples) get bundled in the sdist only, so that works out very nicely.

I've also made sure that the `tox.ini` file is there too -> so you can use `tox` instead of raw `pytest` to run those tests if you want.
It *should* work with a raw `pytest` call too (let me know if it doesn't, I don't have a handy way to do that without a venv...)

I've verified that this works (in a temp folder, with an isolated python, using `setupmeta-*` because the tarball name depends on version...):
```
pip install tox

tar zxf setupmeta-*.tar.gz
cd setupmeta-*
tox -e py
```

**Comment by zsimic** [comment]
Nice! Didn't know about `check-manifest` -> very neat!
Added it to my checks (in the same PR), thanks!

**Comment by zsimic** [comment]
2.8.1 is now released, it should come with everything you need in the sdist

**Comment by jayvdb** [comment]
Thanks; works well.

**Comment by jayvdb** [comment]
https://build.opensuse.org/request/show/845177
