### ISSUE TITLE
Does setupmeta take care of entry points when packaging sdist or bdist_wheel?

### ISSUE THREAD

**Issue by jtmorrisbytes** [zsimic/setupmeta#9]
Hi zsimic, I have another general question. Does setupmeta take care of entry points when building binaries with applications that include an init or main py file? Are there any special actions that I need to take when packaging files with setupmeta installed?

**Comment by jpic** [comment]
Do entrypoints look good when running `python setup.py explain` ?

**Comment by zsimic** [comment]
All setupmeta does is provide a convenience way of specifying your entry points: namely looks for a file called `entry_points.ini`, and exposes it as `entry_points=` named argument to the `setuptools.setup()` call.

This is a very mild added-value: all it does is save you from having to write this:
```
setup(
    ...
    entry_points=...
    ...
)
```

Instead, you create a file `entry_points.ini` (which gets nicely syntax-colored by IDEs typically), with something like this in it:
```
[console_scripts]
my-program = my_package.my_module:my_main
```

That's all it does regarding entry points.

**Comment by blueyed** [comment]
> a file called `entry_points.ini`

Just my 2 cents: I've decided to not use a separate file just for this, since it is something that rarely gets changed/read, and I found that using an extra file (that is visible when listing a directory) is not worth it.
But I can see that it is useful/clearer, and it is nice that setupmeta is flexible enough here for both use cases.
